CREATE TABLE IF NOT EXISTS
BILLIONAIRE (
    ID INT PRIMARY KEY,
    PIC VARCHAR(225),
    NAME VARCHAR(255),
    NET_WORTH DOUBLE,
    COMPANIES_OWNED VARCHAR(255)
);

CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE;