CREATE TABLE IF NOT EXISTS
BILLIONAIRE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    RANK VARCHAR(255),
    NET-WORTH VARCHAR(255)
    COMPANIES-OWNED VARCHAR(255)
);

CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE;